version: "3.7"

services:
  nginx:
    build:
      context: /
      dockerfile: docker/nginx/Dockerfile
    working_dir: /app
    restart: on-failure
    volumes:
      - ./app:delegated
    depends_on:
      - 'php-fpm'
    ports:
      - "80:80"
    environment:
      NGINX_HOST: "localhost:80"
      NGINX_HTTP_PORT: "80"

  php-fpm:
    build:
      context: /
      dockerfile: docker/php/Dockerfile
      target: stateful
      args:
        ENV: dev
        XDEBUG_ENABLED: 1
    working_dir: /app
    restart: on-failure
    volumes:
      - ./app:delegated
    depends_on:
      - 'mysql'
    environment:
      APP_DEBUG: "true"
      DATABASE_URL: "mysql://user:password@mysql:3306/dromupgrade?serverVersion=5.7&charset=utf8"
      PHP_IDE_CONFIG: "serverName=dromupgrade"

  mysql:
    platform: linux/x86_64
    image: mysql:5.7.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - '3306'
    ports:
      - '8092:3306'
    environment:
      MYSQL_DATABASE: "todo_service_dev"
      MYSQL_USER: "ykropchik"
      MYSQL_PASSWORD: "123456789"
      MYSQL_ROOT_PASSWORD: "123456789"
    volumes:
      - mysql-data:/var/lib/mysql:delegated

volumes:
  mysql-data: {}
