version: "3.7"

services:
  nginx:
    build:
      context: server
      dockerfile: docker/nginx/Dockerfile
    working_dir: /app
    restart: on-failure
    volumes:
      - ./server:/app:delegated
    depends_on:
      - 'php-fpm'
    ports:
      - "8091:8080"
    environment:
      NGINX_HOST: "localhost:8091"
      NGINX_HTTP_PORT: "8091"

  php-fpm:
    image: php:ykropchik
    build:
      context: server
      dockerfile: docker/php/Dockerfile
      target: stateless
      args:
        ENV: dev
    working_dir: /app
    restart: on-failure
    volumes:
      - ./server:/app:delegated
    depends_on:
      - 'mysql'
    environment:
      DATABASE_URL: "mysql://ykopchik:123456789@mysql:3306/todo_service_dev?serverVersion=5.7&charset=utf8"

  mysql:
    image: mysql:5.7.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - '3306'
    ports:
      - '8092:3306'
    environment:
      MYSQL_DATABASE: "todo_service_dev"
      MYSQL_USER: "ykropchik"
      MYSQL_PASSWORD: "123456789"
      MYSQL_ROOT_PASSWORD: "123456789"
